import type { Experience } from "@exploravibe/shared";

export const MOCK_EXPERIENCES: Experience[] = [
    {
        id: "jpa-catamara",
        destinationId: "joao-pessoa",
        title: "Passeio de Catamarã ao Pôr do Sol",
        description: "Navegue pelos rios de João Pessoa sob a luz dourada do entardecer.",
        longDescription: "Uma jornada inesquecível pelas águas do Rio Paraíba, passando por bancos de areia e admirando o pôr do sol ao som do Bolero de Ravel no Jacaré. O passeio inclui guia bilíngue e música ambiente.",
        price: 120,
        currency: "BRL",
        images: ["/praia.jpg"],
        category: "Lazer",
        rating: 4.8,
        reviewCount: 45,
        duration: "2h",
        location: { address: "Praia do Jacaré", city: "João Pessoa", state: "PB" },
        commissionRate: 0.12,
    },
    {
        id: "goiania-art-deco",
        destinationId: "goiania",
        title: "Tour Art Déco Histórico",
        description: "Explore o maior acervo Art Déco de Goiânia em um passeio guiado.",
        longDescription: "Caminhada pelo Centro Histórico, visitando o Teatro Goiânia, Estação Ferroviária e Palácio das Esmeraldas. Uma imersão na arquitetura dos anos 30 e 40.",
        price: 90,
        currency: "BRL",
        images: ["https://www.ifg.edu.br/attachments/article/8158/Goiania_Art_Deco.jpg"],
        category: "Cultura",
        rating: 4.7,
        reviewCount: 28,
        duration: "3h",
        location: { address: "Avenida Goiás", city: "Goiânia", state: "GO" },
        commissionRate: 0.12,
    },
    {
        id: "jpa-picaozinho",
        destinationId: "joao-pessoa",
        title: "Piscinas Naturais de Picãozinho",
        description: "Descubra a vida marinha nas águas cristalinas de João Pessoa.",
        longDescription: "Visita às famosas piscinas naturais de Picãozinho, localizadas a poucos quilômetros da costa de Tambaú. Ideal para snorkeling e relaxamento.",
        price: 180,
        currency: "BRL",
        images: ["/praia2.jpg"],
        category: "Cultura",
        rating: 4.9,
        reviewCount: 82,
        duration: "4h",
        location: { address: "Tambaú", city: "João Pessoa", state: "PB" },
        commissionRate: 0.12,
    },
];
